import { useState, useMemo } from 'react'
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from '@/components/ui/select'
import { Switch } from '@/components/ui/switch'

import { useFeeStructureByClass } from '@/hooks/useFeeStructure'
import {
  useCreateFeeSubmission,
  useDeductFees,
  useUpdateFeeSubmission,
} from '@/hooks/useFeeSubmissions'
import { useStudentTransportHistory } from '@/hooks/useTransportHistory'
import { useTransport } from '@/hooks/useTransport'

import { toast } from 'sonner'
import { pdf } from '@react-pdf/renderer'
import FeeReceiptPDF from '@/components/pdfs/FeeReceiptPDF'
import FeeStructureSection from './FeeStructureSection'
import {
  AlertCircle,
  Plus,
  Trash2,
  CheckCircle2,
  Bus,
  BookOpen,
  Clock,
  Receipt,
  CreditCard,
  Info,
} from 'lucide-react'
import { useAllFeeInventory } from '@/hooks/useFeeInventory'

const makeBlankRow = (student) => ({
  id: Date.now() + Math.random(),
  group: '',
  type: '',
  amount: 0,
  paidAmount: undefined,
  includeTuition: true,
  includeTransport: true,
  discount: student?.DiscountAmount ? Number(student.DiscountAmount) : 0,
})

const makeAutoFilledRow = (student, patch = {}) => ({
  id: Date.now() + Math.random(),
  group: '',
  type: '',
  amount: 0,
  paidAmount: undefined,
  includeTuition: true,
  includeTransport: true,
  discount: student?.DiscountAmount ? Number(student.DiscountAmount) : 0,
  autoGenerated: true,
  ...patch,
})

const PAYMENT_MODES = ['Cash', 'UPI', 'Cheque', 'NEFT', 'RTGS', 'DD']

const QUARTER_LABELS = {
  1: { label: 'Q1', months: 'Apr · May · Jun', months_arr: ['apr', 'may', 'jun'] },
  2: { label: 'Q2', months: 'Jul · Aug · Sep', months_arr: ['jul', 'aug', 'sep'] },
  3: { label: 'Q3', months: 'Oct · Nov · Dec', months_arr: ['oct', 'nov', 'dec'] },
  4: { label: 'Q4', months: 'Jan · Feb · Mar', months_arr: ['jan', 'feb', 'mar'] },
}

const GROUP_META = {
  pending_fee: { icon: Clock, label: 'Pending Dues', color: 'text-red-500' },
  tuition_fee: { icon: BookOpen, label: 'Tuition Fee', color: 'text-blue-500' },
  transport_fee: { icon: Bus, label: 'Transport Fee', color: 'text-violet-500' },
  partial_fee: { icon: AlertCircle, label: 'Partial Payments', color: 'text-amber-500' },
  default: { icon: Receipt, label: 'Other Fees', color: 'text-slate-500' },
}

const MONTH_NAMES = [
  'apr',
  'may',
  'jun',
  'jul',
  'aug',
  'sep',
  'oct',
  'nov',
  'dec',
  'jan',
  'feb',
  'mar',
]

function AlertBanner({ icon: Icon, label, value, colorClass, borderClass, bgClass }) {
  return (
    <div
      className={`flex items-center gap-2.5 px-4 py-2.5 rounded-xl border ${borderClass} ${bgClass}`}
    >
      <Icon className={`h-4 w-4 ${colorClass}`} />
      <span className={`text-sm font-medium ${colorClass}`}>{label}</span>
      {value !== undefined && (
        <span className={`text-sm font-bold ml-auto ${colorClass}`}>{value}</span>
      )}
    </div>
  )
}

function ModeButton({ mode, selected, onClick }) {
  return (
    <button
      type="button"
      onClick={() => onClick(mode)}
      className={`px-3 py-1.5 rounded-lg text-sm font-medium border transition-all ${
        selected
          ? 'bg-primary text-primary-foreground border-primary shadow-sm'
          : 'border-border text-muted-foreground hover:border-primary/50 hover:text-foreground'
      }`}
    >
      {mode}
    </button>
  )
}

function SectionLabel({ children }) {
  return (
    <p className="text-[11px] font-semibold uppercase tracking-widest text-muted-foreground">
      {children}
    </p>
  )
}

function getDriverNameFromMonth(monthData) {
  return (
    monthData?.DriverName ||
    monthData?.Driver ||
    monthData?.driverName ||
    monthData?.driver ||
    null
  )
}

function FeeRowCard({
  row,
  index,
  feeGroups,
  getFeesForGroup,
  getTransportFeeForType,
  isRowPartial,
  remainingForRow,
  updateRow,
  removeRow,
  canRemove,
  paidFeeKeys,
}) {
  const feesForGroup = getFeesForGroup(row.group)
  const isTuition = row.type.includes('tuition') || row.type.includes('tution')
  const isTransport = row.group === 'transport_fee'
  const partial = isRowPartial(row)
  const remaining = remainingForRow(row)
  const transportFee = isTuition ? getTransportFeeForType(row.type) : 0

  const selectedTransportOption = isTransport
    ? feesForGroup.find((f) => f.key === row.type)
    : null

  const groupMeta = GROUP_META[row.group] || GROUP_META.default
  const GroupIcon = groupMeta.icon

  return (
    <div
      className={`rounded-2xl border-2 transition-all ${partial ? 'border-amber-300' : 'border-border'}`}
    >
      <div
        className={`flex items-center justify-between px-5 py-3 rounded-t-2xl ${partial ? 'bg-amber-50 dark:bg-amber-950/30' : 'bg-muted/30'}`}
      >
        <div className="flex items-center gap-2">
          <div
            className={`h-6 w-6 rounded-full flex items-center justify-center text-xs font-bold ${partial ? 'bg-amber-400 text-white' : 'bg-primary text-primary-foreground'}`}
          >
            {index + 1}
          </div>
          <span className="text-sm font-semibold text-foreground">
            {row.type
              ? row.type.replace(/_/g, ' ').replace(/fee/gi, '').trim().toUpperCase() +
                ' FEE'
              : 'New Fee Entry'}
          </span>
          {partial && (
            <Badge
              variant="outline"
              className="text-xs border-amber-400 text-amber-600 bg-amber-50"
            >
              Partial · ₹{remaining} remaining
            </Badge>
          )}
          {row.autoGenerated && (
            <Badge
              variant="outline"
              className="text-xs border-blue-400 text-blue-600 bg-blue-50"
            >
              Auto
            </Badge>
          )}
        </div>
        {canRemove && (
          <button
            onClick={() => removeRow(row.id)}
            className="text-muted-foreground hover:text-destructive transition-colors p-1 rounded-md hover:bg-destructive/10"
          >
            <Trash2 className="h-4 w-4" />
          </button>
        )}
      </div>

      <div className="p-5 space-y-5">
        <div className="space-y-2">
          <SectionLabel>Step 1 — Choose the fee</SectionLabel>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <Select
              value={row.group}
              onValueChange={(val) =>
                updateRow(row.id, {
                  group: val,
                  type: '',
                  amount: 0,
                  paidAmount: undefined,
                  autoGenerated: false,
                })
              }
            >
              <SelectTrigger className="h-11">
                <div className="flex items-center gap-2">
                  <GroupIcon className={`h-4 w-4 ${groupMeta.color}`} />
                  <SelectValue placeholder="Fee category" />
                </div>
              </SelectTrigger>
              <SelectContent>
                {feeGroups.map((g) => {
                  const meta = GROUP_META[g] || GROUP_META.default
                  const GIcon = meta.icon
                  return (
                    <SelectItem key={g} value={g}>
                      <span className="flex items-center gap-2">
                        <GIcon className={`h-3.5 w-3.5 ${meta.color}`} />
                        {g === 'partial_fee'
                          ? '⚠ Partial Payments'
                          : g
                              .replace('_fee', '')
                              .replace(/_/g, ' ')
                              .replace(/tuition|tution/i, 'Tuition')
                              .toUpperCase() + ' FEE'}
                      </span>
                    </SelectItem>
                  )
                })}
              </SelectContent>
            </Select>

            <Select
              value={row.type}
              disabled={!row.group}
              onValueChange={(val) => {
                const fee = feesForGroup.find((f) => f.key === val)
                updateRow(row.id, {
                  type: val,
                  amount: fee?.value || 0,
                  paidAmount: undefined,
                  autoGenerated: false,
                })
              }}
            >
              <SelectTrigger className="h-11">
                <SelectValue
                  placeholder={
                    row.group ? 'Select month / type' : 'Pick a category first'
                  }
                />
              </SelectTrigger>
              <SelectContent>
                {feesForGroup.map(({ key, label, value, noRoute, noFee }) => {
                  const isPaid =
                    paidFeeKeys.has(key) || paidFeeKeys.has(key.replace('_fee', ''))
                  const isUnavailable = noRoute || noFee
                  const isDisabled = isPaid || isUnavailable
                  return (
                    <SelectItem
                      key={key}
                      value={key}
                      disabled={isDisabled}
                      className={isDisabled ? 'opacity-60 cursor-not-allowed' : ''}
                    >
                      <span className="flex items-center justify-between gap-4 w-full">
                        <span className="flex items-center gap-2">
                          {isPaid && (
                            <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500 shrink-0" />
                          )}
                          <span
                            className={
                              isPaid
                                ? 'text-muted-foreground line-through'
                                : isUnavailable
                                  ? 'text-muted-foreground'
                                  : ''
                            }
                          >
                            {label}
                          </span>
                          {isPaid && (
                            <Badge
                              variant="outline"
                              className="text-[10px] px-1.5 py-0 border-emerald-400 text-emerald-600"
                            >
                              Paid
                            </Badge>
                          )}
                          {!isPaid && isUnavailable && (
                            <Badge
                              variant="outline"
                              className="text-[10px] px-1.5 py-0 border-slate-300 text-slate-400"
                            >
                              {noRoute ? 'No route' : 'Not set'}
                            </Badge>
                          )}
                        </span>
                        <span className="text-muted-foreground font-mono text-xs">
                          {isUnavailable
                            ? '—'
                            : `₹${Number(value).toLocaleString('en-IN')}`}
                        </span>
                      </span>
                    </SelectItem>
                  )
                })}
              </SelectContent>
            </Select>
          </div>
        </div>

        {row.type && (
          <div className="space-y-2">
            <SectionLabel>Step 2 — Confirm amount</SectionLabel>
            <div className="rounded-xl border bg-muted/20 p-4 space-y-1">
              {isTuition && (
                <>
                  <div className="flex items-center justify-between py-1">
                    <div className="flex items-center gap-2">
                      <Switch
                        checked={row.includeTuition}
                        onCheckedChange={(val) =>
                          updateRow(row.id, { includeTuition: val, autoGenerated: false })
                        }
                        className="scale-90"
                      />
                      <span className="text-sm flex items-center gap-1.5">
                        <BookOpen className="h-3.5 w-3.5 text-blue-500" /> Tuition
                      </span>
                    </div>
                    <span className="text-sm font-mono">
                      ₹{Number(row.amount || 0).toLocaleString('en-IN')}
                    </span>
                  </div>

                  {row.discount > 0 && row.includeTuition && (
                    <div className="flex justify-between items-center py-0.5">
                      <span className="text-sm text-emerald-600">
                        Scholarship / Discount
                      </span>
                      <span className="text-sm font-mono text-emerald-600">
                        − ₹{row.discount.toLocaleString('en-IN')}
                      </span>
                    </div>
                  )}

                  <div className="flex items-center justify-between py-1">
                    <div className="flex items-center gap-2">
                      <Switch
                        checked={row.includeTransport}
                        onCheckedChange={(val) =>
                          updateRow(row.id, {
                            includeTransport: val,
                            autoGenerated: false,
                          })
                        }
                        className="scale-90"
                      />
                      <span className="text-sm flex items-center gap-1.5">
                        <Bus className="h-3.5 w-3.5 text-violet-500" /> Transport
                      </span>
                    </div>
                    <span className="text-sm font-mono">
                      {row.includeTransport && transportFee > 0 ? (
                        `₹${transportFee.toLocaleString('en-IN')}`
                      ) : (
                        <span className="text-muted-foreground text-xs">
                          Not applicable
                        </span>
                      )}
                    </span>
                  </div>

                  <div className="border-t pt-3 mt-2 flex items-center justify-between">
                    <span className="text-sm font-semibold">Amount to collect</span>
                    <Input
                      type="number"
                      min={0}
                      value={
                        row.paidAmount !== undefined
                          ? row.paidAmount
                          : (row.includeTuition
                              ? Math.max(Number(row.amount) - row.discount, 0)
                              : 0) + (row.includeTransport ? transportFee : 0)
                      }
                      onChange={(e) =>
                        updateRow(row.id, {
                          paidAmount: Number(e.target.value),
                          autoGenerated: false,
                        })
                      }
                      className={`w-32 text-right font-bold h-9 ${partial ? 'border-amber-400 text-amber-700' : ''}`}
                    />
                  </div>

                  {partial && (
                    <div className="flex items-center gap-2 mt-1 pt-2 border-t border-amber-200">
                      <Info className="h-3.5 w-3.5 text-amber-500 shrink-0" />
                      <p className="text-xs text-amber-600">
                        ₹{remaining} is less than the full amount — this will be saved as
                        a <strong>partial payment</strong>. The balance can be collected
                        later.
                      </p>
                    </div>
                  )}
                </>
              )}

              {!isTuition && isTransport && selectedTransportOption && (
                <div className="space-y-2">
                  <div className="flex items-center gap-2 flex-wrap">
                    <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-violet-100 dark:bg-violet-900/40 border border-violet-200 dark:border-violet-800">
                      <Bus className="h-3 w-3 text-violet-600" />
                      <span className="text-xs font-medium text-violet-700 dark:text-violet-300">
                        Route: {selectedTransportOption.route}
                      </span>
                    </div>

                    {selectedTransportOption.vehicleNo && (
                      <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700">
                        <span className="text-xs text-muted-foreground">Vehicle:</span>
                        <span className="text-xs font-semibold">
                          {selectedTransportOption.vehicleNo}
                        </span>
                      </div>
                    )}

                    {selectedTransportOption.driverName && (
                      <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-800">
                        <span className="text-xs text-muted-foreground">Driver:</span>
                        <span className="text-xs font-semibold text-emerald-700 dark:text-emerald-300">
                          {selectedTransportOption.driverName}
                        </span>
                      </div>
                    )}
                  </div>

                  <div className="flex items-center justify-between pt-1 border-t">
                    <span className="text-sm text-muted-foreground">Transport Fee</span>
                    <span className="text-lg font-bold font-mono text-violet-600">
                      ₹{Number(row.amount || 0).toLocaleString('en-IN')}
                    </span>
                  </div>
                </div>
              )}

              {!isTuition && !isTransport && (
                <div className="flex items-center justify-between">
                  <span className="text-sm text-muted-foreground">Fee Amount</span>
                  <span className="text-lg font-bold font-mono">
                    ₹{Number(row.amount || 0).toLocaleString('en-IN')}
                  </span>
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

function QuarterCard({ q, label, months, selected, onClick }) {
  return (
    <button
      type="button"
      onClick={() => onClick(String(q))}
      className={`rounded-xl border-2 p-4 text-left transition-all ${
        selected ? 'border-primary bg-primary/5' : 'border-border hover:border-primary/40'
      }`}
    >
      <div className="flex items-start justify-between">
        <div>
          <p
            className={`text-base font-bold ${selected ? 'text-primary' : 'text-foreground'}`}
          >
            {label}
          </p>
          <p className="text-xs text-muted-foreground mt-0.5">{months}</p>
        </div>
        {selected && <CheckCircle2 className="h-5 w-5 text-primary" />}
      </div>
    </button>
  )
}

export default function PayFeesSection({ student, feesData }) {
  const academicYear = '2025-2026'

  const [tab, setTab] = useState('type')
  const [quarter, setQuarter] = useState('')
  const [collectionDate] = useState(new Date().toISOString().split('T')[0])
  const [includeTuition, setIncludeTuition] = useState(true)
  const [includeTransport, setIncludeTransport] = useState(true)
  const [quarterPaymentMode, setQuarterPaymentMode] = useState('')

  const [commonPaymentMode, setCommonPaymentMode] = useState('')
  const [commonRemarks, setCommonRemarks] = useState('')
  const [commonCollectedAmount, setCommonCollectedAmount] = useState('')
  const [feeRows, setFeeRows] = useState([makeBlankRow(student)])

  const { data: structure } = useFeeStructureByClass({
    classId: student?.ClassID,
    academicYear,
    enabled: !!student?.ClassID,
  })
  const { data: transportHistory } = useStudentTransportHistory({
    studentId: student?.StudentID,
    academicYear,
    enabled: !!student?.StudentID,
  })
  const { data: transport } = useTransport()
  const { data: inventory } = useAllFeeInventory()
  console.log(inventory)

  const { mutate: createFeeSubmission, isLoading } = useCreateFeeSubmission()
  const { mutate: deductFees } = useDeductFees()
  const { mutate: updateFeeSubmission } = useUpdateFeeSubmission()

  const pendingAmount = Number(student?.PendingFee || 0)

  const transportRoutePrice = useMemo(() => {
    if (!transportHistory?.months?.length || !transport?.length) return 0
    const routeMonth = transportHistory.months.find((m) => m?.Route && m.Route !== 'N/A')
    if (!routeMonth) return 0
    const routeTransport = transport.find(
      (t) => t?.TransportNumber === routeMonth.VehicleNo
    )
    return Number(routeTransport?.Price ?? 0)
  }, [transportHistory, transport])

  const partialFees = useMemo(() => {
    if (!feesData?.data) return []
    const seen = new Set()
    return feesData.data.filter((f) => {
      if ((f.PaymentStatus || '').toUpperCase() !== 'PARTIAL') return false
      const id = f.SubmissionID ?? f.id
      if (seen.has(id)) return false
      seen.add(id)
      return true
    })
  }, [feesData])

  const paidFeeKeys = useMemo(() => {
    if (!feesData?.data) return new Set()
    const paid = new Set()
    feesData.data.forEach((f) => {
      const status = (f.PaymentStatus || '').toUpperCase()
      if (status !== 'SUCCESS') return
      const raw = (f.FeeType || '').toLowerCase().replace(/\s+/g, '_')
      const key = raw.endsWith('_fee') ? raw : `${raw}_fee`
      paid.add(key)
      paid.add(raw)
      if (raw.startsWith('transport_')) paid.add(raw)
    })
    return paid
  }, [feesData])

  const feeGroups = useMemo(() => {
    if (!structure && !inventory?.length) return []

    const groups = [
      ...new Set(
        Object.keys(structure || {})
          .filter((k) => k.includes('_fee'))
          .map((k) => (k.includes('tuition') || k.includes('tution') ? 'tuition_fee' : k))
      ),
    ]

    const base = ['pending_fee', ...groups]

    if (transportHistory?.months?.length) {
      const tuitionIdx = base.indexOf('tuition_fee')
      base.splice(tuitionIdx !== -1 ? tuitionIdx + 1 : 1, 0, 'transport_fee')
    }

    if (partialFees.length > 0) base.push('partial_fee')

    // ✅ FIXED
    if (Array.isArray(inventory) && inventory.length > 0) {
      base.push('inventory_fee')
    }

    return [...new Set(base)]
  }, [structure, partialFees, transportHistory, inventory])

  const applicableInventory = useMemo(() => {
    if (!Array.isArray(inventory)) return []

    return inventory.filter((item) => {
      return (
        // ⚠️ TEMP: comment this if mismatch
        // item.academic_year === academicYear &&

        item.class === '' || String(item.class).trim() === String(student.ClassID).trim()
      )
    })
  }, [inventory, student, academicYear])

  const quarterTotal = useMemo(() => {
    if (!quarter || !structure) return 0
    const months = QUARTER_LABELS[quarter]?.months_arr || []
    let total = 0
    months.forEach((month) => {
      const tuitionKey = Object.keys(structure).find(
        (k) => k.startsWith(month) && (k.includes('tuition') || k.includes('tution'))
      )
      if (tuitionKey && includeTuition) total += Number(structure[tuitionKey] || 0)
      const monthTransport = transportHistory?.months?.find((m) =>
        m.MonthName?.toLowerCase().startsWith(month)
      )
      if (includeTransport && monthTransport?.Route && monthTransport.Route !== 'N/A') {
        total += Number(transportRoutePrice || 0)
      }
    })
    return total
  }, [
    quarter,
    structure,
    transportHistory,
    transportRoutePrice,
    includeTuition,
    includeTransport,
  ])

  const getFeesForGroup = (group) => {
    if (!group || !structure) return []

    if (group === 'inventory_fee') {
      return applicableInventory.map((item) => ({
        key: `inventory_${item.fee_type}`,
        label: `${item.fee_type} ${
          item.class === '' ? '(All Classes)' : `(Class ${item.class})`
        }`,
        value: Number(item.price || 0),
      }))
    }

    if (group === 'pending_fee') {
      return [{ key: 'pending_fee', label: 'PENDING FEES', value: pendingAmount }]
    }

    if (group === 'partial_fee') {
      return partialFees.map((f) => {
        const discount = student?.DiscountAmount ? Number(student.DiscountAmount) : 0
        const remaining = Math.max(
          Number(f.OriginalAmount || 0) - discount - Number(f.PaidAmount || 0),
          0
        )
        return {
          key: `partial_${f.SubmissionID ?? f.id}`,
          label: `${f.FeeType} (₹${remaining} left)`,
          value: remaining,
          submissionId: f.SubmissionID ?? f.id,
          originalFeeType: f.FeeType,
        }
      })
    }

    if (group === 'transport_fee') {
      return MONTH_NAMES.map((month) => {
        const monthData = transportHistory?.months?.find((m) =>
          m.MonthName?.toLowerCase().startsWith(month)
        )
        const hasRoute = monthData?.Route && monthData.Route !== 'N/A'
        return {
          key: `transport_${month}`,
          label: `${month.charAt(0).toUpperCase() + month.slice(1)} Transport Fee`,
          value: hasRoute ? transportRoutePrice : 0,
          route: hasRoute ? monthData.Route : null,
          vehicleNo: hasRoute ? monthData.VehicleNo : null,
          driverName: hasRoute ? getDriverNameFromMonth(monthData) : null,
          noRoute: !hasRoute,
        }
      })
    }

    if (group === 'tuition_fee') {
      return MONTH_NAMES.map((month) => {
        const tuitionKey = Object.keys(structure).find(
          (k) => k.startsWith(month) && (k.includes('tuition') || k.includes('tution'))
        )
        const value = tuitionKey ? Number(structure[tuitionKey] || 0) : 0
        return {
          key: tuitionKey ?? `${month}_tuition_fee`,
          label: `${month.charAt(0).toUpperCase() + month.slice(1)} Tuition Fee`,
          value,
          noFee: !tuitionKey,
        }
      })
    }

    return Object.entries(structure)
      .filter(([key]) => key === group)
      .map(([key, value]) => ({
        key,
        label: key.replace(/_/g, ' ').toUpperCase(),
        value,
      }))
  }

  const getTransportFeeForType = (type) => {
    if (!type) return 0
    const month = type.split('_')[0]
    const monthData = transportHistory?.months?.find((m) =>
      m.MonthName?.toLowerCase().startsWith(month)
    )
    if (monthData?.Route && monthData.Route !== 'N/A')
      return Number(transportRoutePrice || 0)
    return 0
  }

  const calculateRowPayable = (row) => {
    const isTuition = row.type.includes('tuition') || row.type.includes('tution')
    if (!isTuition) return Math.max(Number(row.amount || 0), 0)

    let total = 0
    if (row.includeTuition) {
      total +=
        row.paidAmount !== undefined
          ? Math.max(Number(row.paidAmount || 0), 0)
          : Math.max(Number(row.amount || 0) - Number(row.discount || 0), 0)
    }
    if (row.includeTransport) total += getTransportFeeForType(row.type)
    return Math.max(total, 0)
  }

  const isRowPartial = (row) => {
    const isTuition = row.type.includes('tuition') || row.type.includes('tution')
    if (!isTuition || !row.includeTuition || row.paidAmount === undefined) return false
    const full = Math.max(Number(row.amount || 0) - Number(row.discount || 0), 0)
    return Number(row.paidAmount || 0) < full
  }

  const remainingForRow = (row) => {
    const full = Math.max(Number(row.amount || 0) - Number(row.discount || 0), 0)
    const paid = Math.max(Number(row.paidAmount ?? full), 0)
    return Math.max(full - paid, 0)
  }

  const grandTotal = useMemo(() => {
    return feeRows.reduce((sum, row) => sum + calculateRowPayable(row), 0)
  }, [feeRows, transportRoutePrice, transportHistory])

  const updateRow = (id, patch) =>
    setFeeRows((prev) => prev.map((r) => (r.id === id ? { ...r, ...patch } : r)))

  const addRow = () => setFeeRows((prev) => [...prev, makeBlankRow(student)])
  const removeRow = (id) =>
    setFeeRows((prev) => {
      const next = prev.filter((r) => r.id !== id)
      return next.length ? next : [makeBlankRow(student)]
    })

  const clearGeneratedRows = () => {
    setFeeRows([makeBlankRow(student)])
  }

  const autoGenerateRowsFromAmount = () => {
    const total = Math.max(Number(commonCollectedAmount || 0), 0)

    if (!total) {
      toast.error('Please enter total collected amount')
      return
    }

    if (!structure) {
      toast.error('Fee structure not loaded')
      return
    }

    let remaining = total
    const rows = []
    const studentDiscount = Number(student?.DiscountAmount || 0)

    for (const month of MONTH_NAMES) {
      if (remaining <= 0) break

      const tuitionKey = Object.keys(structure).find(
        (k) => k.startsWith(month) && (k.includes('tuition') || k.includes('tution'))
      )

      if (!tuitionKey) continue

      const alreadyPaid =
        paidFeeKeys.has(tuitionKey) ||
        paidFeeKeys.has(month) ||
        paidFeeKeys.has(`${month}_tuition`)

      if (alreadyPaid) continue

      const tuitionAmount = Number(structure[tuitionKey] || 0)
      const tuitionNet = Math.max(tuitionAmount - studentDiscount, 0)

      const monthTransport = transportHistory?.months?.find((m) =>
        m.MonthName?.toLowerCase().startsWith(month)
      )

      const hasTransport = !!monthTransport?.Route && monthTransport.Route !== 'N/A'
      const transportAmount = hasTransport ? Number(transportRoutePrice || 0) : 0

      if (hasTransport && transportAmount > 0 && remaining >= transportAmount) {
        rows.push(
          makeAutoFilledRow(student, {
            group: 'transport_fee',
            type: `transport_${month}`,
            amount: transportAmount,
            paidAmount: transportAmount,
            includeTuition: false,
            includeTransport: true,
          })
        )
        remaining -= transportAmount
      }

      if (tuitionNet > 0 && remaining > 0) {
        const tuitionPaid = Math.min(remaining, tuitionNet)

        rows.push(
          makeAutoFilledRow(student, {
            group: 'tuition_fee',
            type: tuitionKey,
            amount: tuitionAmount,
            paidAmount: tuitionPaid,
            includeTuition: true,
            includeTransport: false,
            discount: studentDiscount,
          })
        )

        remaining -= tuitionPaid
      }
    }

    if (!rows.length) {
      toast.error('No fee rows could be created from this amount')
      return
    }

    setFeeRows(rows)
    toast.success('Fee rows added automatically')
  }

  const handleDownloadSlip = async (submissions) => {
    const receiptNo = `RCP-${Date.now().toString().slice(-6)}`
    const feeMonth = new Date().toLocaleString('en-IN', { month: 'short' }).toUpperCase()
    const blob = await pdf(
      <FeeReceiptPDF
        student={student}
        submissions={submissions}
        receiptNo={receiptNo}
        feeMonth={feeMonth}
      />
    ).toBlob()
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `fee-receipt-${student?.FullName ?? 'student'}-${receiptNo}.pdf`
    a.click()
    URL.revokeObjectURL(url)
  }

  const handleSubmit = async () => {
    const baseTxn = `TXN${Date.now()}`
    const collectedSubmissions = []
    const basePayload = {
      studentId: Number(student.StudentID),
      paymentStatus: 'SUCCESS',
      submittedBy: 'Accountant',
      submittedDate: collectionDate,
    }

    if (tab === 'quarter') {
      if (!quarter) {
        toast.error('Please select a quarter')
        return
      }

      const months = QUARTER_LABELS[quarter]?.months_arr || []

      months.forEach((month) => {
        const tuitionKey = Object.keys(structure || {}).find(
          (k) => k.startsWith(month) && (k.includes('tuition') || k.includes('tution'))
        )

        if (tuitionKey && includeTuition) {
          const tuitionAmount = Number(structure[tuitionKey] || 0)
          collectedSubmissions.push({
            FeeType: `${month.toUpperCase()} Tuition Fee`,
            OriginalAmount: tuitionAmount,
            DiscountAmount: 0,
            PaidAmount: tuitionAmount,
            PaymentMethod: quarterPaymentMode || 'CASH',
            PaymentDate: collectionDate,
            SubmittedDate: collectionDate,
          })
          createFeeSubmission({
            ...basePayload,
            paymentMode: quarterPaymentMode || 'CASH',
            remarks: 'Quarterly Payment',
            feeType: `${month.toUpperCase()}_TUITION`,
            transactionId: `${baseTxn}_${month}_TUITION`,
            originalAmount: tuitionAmount,
            discountAmount: 0,
            paidAmount: tuitionAmount,
          })
        }

        const monthTransport = transportHistory?.months?.find((m) =>
          m.MonthName?.toLowerCase().startsWith(month)
        )
        if (includeTransport && monthTransport?.Route && monthTransport.Route !== 'N/A') {
          collectedSubmissions.push({
            FeeType: `${month.toUpperCase()} Transport Fee`,
            OriginalAmount: transportRoutePrice,
            DiscountAmount: 0,
            PaidAmount: transportRoutePrice,
            PaymentMethod: quarterPaymentMode || 'CASH',
            PaymentDate: collectionDate,
            SubmittedDate: collectionDate,
          })
          createFeeSubmission({
            ...basePayload,
            paymentMode: quarterPaymentMode || 'CASH',
            remarks: 'Quarterly Payment',
            feeType: `TRANSPORT_${month.toUpperCase()}`,
            transactionId: `${baseTxn}_${month}_TRANSPORT`,
            originalAmount: transportRoutePrice,
            discountAmount: 0,
            paidAmount: transportRoutePrice,
          })
        }
      })

      toast.success('Quarter fees collected successfully')
      if (collectedSubmissions.length > 0) await handleDownloadSlip(collectedSubmissions)
      return
    }

    if (!commonPaymentMode) {
      toast.error('Please select payment mode')
      return
    }

    if (!feeRows.some((r) => r.type)) {
      toast.error('Please add fee rows first')
      return
    }

    let hasPartialRows = false

    for (const row of feeRows) {
      if (!row.type) continue

      const isTuition = row.type.includes('tuition') || row.type.includes('tution')
      const isTransportGroup = row.group === 'transport_fee'
      const isPending = row.type === 'pending_fee'
      const isPartialGroup = row.group === 'partial_fee'
      const isInventory = row.group === 'inventory_fee'
      const month = row.type.split('_')[0]

      if (isInventory) {
        const amount = Number(row.amount)
        if (!amount) continue

        const feeLabel = row.type.replace('inventory_', '').toUpperCase()

        collectedSubmissions.push({
          FeeType: feeLabel,
          OriginalAmount: amount,
          DiscountAmount: 0,
          PaidAmount: amount,
          PaymentMethod: commonPaymentMode,
          PaymentDate: collectionDate,
          SubmittedDate: collectionDate,
        })

        createFeeSubmission({
          ...basePayload,
          paymentMode: commonPaymentMode,
          remarks: commonRemarks,
          feeType: feeLabel,
          transactionId: `${baseTxn}_${row.id}`,
          originalAmount: amount,
          discountAmount: 0,
          paidAmount: amount,
        })

        continue
      }

      if (isPartialGroup) {
        const remainingAmount = Number(row.amount)
        const submissionId = Number(row.type.replace('partial_', ''))
        const originalRecord = partialFees.find(
          (f) => (f.SubmissionID ?? f.id) === submissionId
        )
        const feeTypeLabel = originalRecord?.FeeType ?? row.type

        collectedSubmissions.push({
          FeeType: feeTypeLabel,
          OriginalAmount: remainingAmount,
          DiscountAmount: 0,
          PaidAmount: remainingAmount,
          PaymentMethod: commonPaymentMode,
          PaymentDate: collectionDate,
          SubmittedDate: collectionDate,
        })

        createFeeSubmission({
          ...basePayload,
          paymentMode: commonPaymentMode,
          remarks: commonRemarks || 'Partial fee completion',
          feeType: feeTypeLabel.toUpperCase().replace(/\s+/g, '_'),
          transactionId: `${baseTxn}_P${String(row.id).slice(-4)}`,
          originalAmount: remainingAmount,
          discountAmount: 0,
          paidAmount: remainingAmount,
          paymentStatus: 'SUCCESS',
        })

        if (submissionId)
          updateFeeSubmission({ id: submissionId, paymentStatus: 'SUCCESS' })
        continue
      }

      if (isPending) {
        const amount = Number(row.amount)
        if (!amount) continue

        collectedSubmissions.push({
          FeeType: 'Pending Fee',
          OriginalAmount: amount,
          DiscountAmount: 0,
          PaidAmount: amount,
          PaymentMethod: commonPaymentMode,
          PaymentDate: collectionDate,
          SubmittedDate: collectionDate,
        })

        createFeeSubmission({
          ...basePayload,
          paymentMode: commonPaymentMode,
          remarks: commonRemarks,
          feeType: 'PENDING_FEE',
          transactionId: `${baseTxn}_PENDING_${row.id}`,
          originalAmount: amount,
          discountAmount: 0,
          paidAmount: amount,
        })

        deductFees({
          studentId: Number(student.StudentID),
          amount,
          paymentMode: commonPaymentMode,
          remarks: commonRemarks,
          submittedDate: collectionDate,
        })
        continue
      }

      if (isTransportGroup) {
        const amount = Number(row.amount)
        if (!amount) continue
        const tMonth = row.type.replace('transport_', '')

        collectedSubmissions.push({
          FeeType: `${tMonth.toUpperCase()} Transport Fee`,
          OriginalAmount: amount,
          DiscountAmount: 0,
          PaidAmount: amount,
          PaymentMethod: commonPaymentMode,
          PaymentDate: collectionDate,
          SubmittedDate: collectionDate,
        })

        createFeeSubmission({
          ...basePayload,
          paymentMode: commonPaymentMode,
          remarks: commonRemarks,
          feeType: `TRANSPORT_${tMonth.toUpperCase()}`,
          transactionId: `${baseTxn}_${tMonth}_TRANSPORT`,
          originalAmount: amount,
          discountAmount: 0,
          paidAmount: amount,
        })
        continue
      }

      if (isTuition) {
        if (row.includeTuition) {
          const originalAmount = Number(row.amount)
          const discountAmount = Number(row.discount || 0)
          const fullPayable = Math.max(originalAmount - discountAmount, 0)
          const paidAmount =
            row.paidAmount !== undefined
              ? Math.max(Number(row.paidAmount || 0), 0)
              : fullPayable
          const partial = paidAmount < fullPayable
          if (partial) hasPartialRows = true

          collectedSubmissions.push({
            FeeType: `${month.toUpperCase()} Tuition Fee`,
            OriginalAmount: originalAmount,
            DiscountAmount: discountAmount,
            PaidAmount: paidAmount,
            PaymentMethod: commonPaymentMode,
            PaymentDate: collectionDate,
            SubmittedDate: collectionDate,
            PaymentStatus: partial ? 'PARTIAL' : 'SUCCESS',
          })

          createFeeSubmission({
            ...basePayload,
            paymentMode: commonPaymentMode,
            remarks: commonRemarks,
            feeType: `${month.toUpperCase()}_TUITION`,
            transactionId: `${baseTxn}_${month}_TUITION`,
            originalAmount,
            discountAmount,
            paidAmount,
            paymentStatus: partial ? 'PARTIAL' : 'SUCCESS',
          })
        }

        if (row.includeTransport) {
          const transportFee = getTransportFeeForType(row.type)
          if (transportFee > 0) {
            collectedSubmissions.push({
              FeeType: `${month.toUpperCase()} Transport Fee`,
              OriginalAmount: transportFee,
              DiscountAmount: 0,
              PaidAmount: transportFee,
              PaymentMethod: commonPaymentMode,
              PaymentDate: collectionDate,
              SubmittedDate: collectionDate,
            })
            createFeeSubmission({
              ...basePayload,
              paymentMode: commonPaymentMode,
              remarks: commonRemarks,
              feeType: `TRANSPORT_${month.toUpperCase()}`,
              transactionId: `${baseTxn}_${month}_TRANSPORT`,
              originalAmount: transportFee,
              discountAmount: 0,
              paidAmount: transportFee,
            })
          }
        }
        continue
      }

      const amount = Number(row.amount)
      if (!amount) continue

      collectedSubmissions.push({
        FeeType: row.type.replace(/_/g, ' ').toUpperCase(),
        OriginalAmount: amount,
        DiscountAmount: 0,
        PaidAmount: amount,
        PaymentMethod: commonPaymentMode,
        PaymentDate: collectionDate,
        SubmittedDate: collectionDate,
      })

      createFeeSubmission({
        ...basePayload,
        paymentMode: commonPaymentMode,
        remarks: commonRemarks,
        feeType: row.type.replace('_fee', '').toUpperCase(),
        transactionId: `${baseTxn}_${row.id}`,
        originalAmount: amount,
        discountAmount: 0,
        paidAmount: amount,
      })
    }

    if (hasPartialRows)
      toast.warning('Partial payment recorded — remaining balance saved as partial fee')
    else toast.success('Fees collected successfully')

    if (collectedSubmissions.length > 0) await handleDownloadSlip(collectedSubmissions)
  }

  console.log('feeGroups →', feeGroups)

  return (
    <>
      <Card className="rounded-2xl shadow-sm">
        <CardHeader className="pb-4">
          <div className="flex items-center justify-between flex-wrap gap-3">
            <CardTitle className="text-xl">Collect Fees</CardTitle>
            <div className="flex items-center gap-2 flex-wrap">
              {pendingAmount > 0 && (
                <AlertBanner
                  icon={AlertCircle}
                  label="Pending dues"
                  value={`₹${pendingAmount.toLocaleString('en-IN')}`}
                  colorClass="text-red-600 dark:text-red-400"
                  borderClass="border-red-200 dark:border-red-800"
                  bgClass="bg-red-50 dark:bg-red-950"
                />
              )}
              {partialFees.length > 0 && (
                <AlertBanner
                  icon={AlertCircle}
                  label={`${partialFees.length} partial payment${partialFees.length > 1 ? 's' : ''} pending`}
                  colorClass="text-amber-600 dark:text-amber-400"
                  borderClass="border-amber-200 dark:border-amber-800"
                  bgClass="bg-amber-50 dark:bg-amber-950"
                />
              )}
            </div>
          </div>

          <div className="flex gap-1 mt-4 p-1 bg-muted rounded-xl w-fit">
            {[
              { id: 'type', label: 'By Fee Type', icon: Receipt },
              { id: 'quarter', label: 'Full Quarter', icon: CreditCard },
            ].map(({ id, label, icon: Icon }) => (
              <button
                key={id}
                onClick={() => setTab(id)}
                className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all ${
                  tab === id
                    ? 'bg-background shadow text-foreground'
                    : 'text-muted-foreground hover:text-foreground'
                }`}
              >
                <Icon className="h-3.5 w-3.5" />
                {label}
              </button>
            ))}
          </div>
        </CardHeader>

        <CardContent className="space-y-4">
          {tab === 'type' && (
            <>
              <div className="rounded-2xl border bg-muted/20 p-5 space-y-4">
                <SectionLabel>Quick amount entry</SectionLabel>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  <div>
                    <p className="text-xs text-muted-foreground mb-2">
                      Total collected amount
                    </p>
                    <Input
                      type="number"
                      min={0}
                      placeholder="Enter total amount"
                      value={commonCollectedAmount}
                      onChange={(e) => setCommonCollectedAmount(e.target.value)}
                      className="h-10 text-sm font-semibold"
                    />
                  </div>

                  <div className="flex items-end gap-2">
                    <Button
                      type="button"
                      onClick={autoGenerateRowsFromAmount}
                      className="rounded-xl gap-2"
                    >
                      <Plus className="h-4 w-4" />
                      Add Fee
                    </Button>

                    <Button
                      type="button"
                      variant="outline"
                      onClick={clearGeneratedRows}
                      className="rounded-xl gap-2"
                    >
                      <Trash2 className="h-4 w-4" />
                      Clear
                    </Button>
                  </div>
                </div>
              </div>

              <div className="space-y-3">
                {feeRows.map((row, index) => (
                  <FeeRowCard
                    key={row.id}
                    row={row}
                    index={index}
                    feeGroups={feeGroups}
                    getFeesForGroup={getFeesForGroup}
                    getTransportFeeForType={getTransportFeeForType}
                    isRowPartial={isRowPartial}
                    remainingForRow={remainingForRow}
                    updateRow={updateRow}
                    removeRow={removeRow}
                    canRemove={feeRows.length > 1}
                    paidFeeKeys={paidFeeKeys}
                  />
                ))}
              </div>

              <button
                onClick={addRow}
                className="flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors border-2 border-dashed border-border hover:border-primary/40 rounded-xl w-full py-3 justify-center"
              >
                <Plus className="h-4 w-4" />
                Add another fee entry manually
              </button>

              {feeRows.some((r) => r.type) && (
                <div className="rounded-2xl border bg-primary/5 border-primary/20 p-4 mt-2">
                  <SectionLabel>Summary</SectionLabel>
                  <div className="mt-2 space-y-0.5">
                    {feeRows
                      .filter((r) => r.type)
                      .map((r) => (
                        <div key={r.id} className="flex justify-between text-sm py-0.5">
                          <span className="text-muted-foreground">
                            {r.type
                              .replace(/_/g, ' ')
                              .replace(/fee/gi, '')
                              .trim()
                              .toUpperCase()}{' '}
                            FEE
                          </span>
                          <span className="font-mono">
                            ₹{calculateRowPayable(r).toLocaleString('en-IN')}
                          </span>
                        </div>
                      ))}
                    <div className="flex justify-between items-center pt-2 border-t">
                      <span className="font-semibold">Total to collect</span>
                      <span className="text-lg font-bold text-primary font-mono">
                        ₹{grandTotal.toLocaleString('en-IN')}
                      </span>
                    </div>
                  </div>
                </div>
              )}
            </>
          )}

          {tab === 'quarter' && (
            <div className="space-y-5">
              <div>
                <SectionLabel>Select quarter</SectionLabel>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-2">
                  {Object.entries(QUARTER_LABELS).map(([q, { label, months }]) => (
                    <QuarterCard
                      key={q}
                      q={q}
                      label={label}
                      months={months}
                      selected={quarter === String(q)}
                      onClick={setQuarter}
                    />
                  ))}
                </div>
              </div>

              <div className="rounded-2xl border bg-muted/20 p-5 space-y-4">
                <SectionLabel>What to include</SectionLabel>
                <div className="flex items-center gap-6">
                  <label className="flex items-center gap-2 cursor-pointer">
                    <Switch
                      checked={includeTuition}
                      onCheckedChange={setIncludeTuition}
                    />
                    <span className="text-sm flex items-center gap-1.5">
                      <BookOpen className="h-3.5 w-3.5 text-blue-500" /> Tuition Fees
                    </span>
                  </label>
                  <label className="flex items-center gap-2 cursor-pointer">
                    <Switch
                      checked={includeTransport}
                      onCheckedChange={setIncludeTransport}
                    />
                    <span className="text-sm flex items-center gap-1.5">
                      <Bus className="h-3.5 w-3.5 text-violet-500" /> Transport Fees
                    </span>
                  </label>
                </div>

                <div>
                  <SectionLabel>Payment mode</SectionLabel>
                  <div className="flex flex-wrap gap-2 mt-2">
                    {PAYMENT_MODES.map((m) => (
                      <ModeButton
                        key={m}
                        mode={m}
                        selected={quarterPaymentMode === m}
                        onClick={setQuarterPaymentMode}
                      />
                    ))}
                  </div>
                </div>

                {quarter && (
                  <div className="rounded-xl border p-4 bg-background space-y-1">
                    <SectionLabel>
                      {QUARTER_LABELS[quarter]?.label} — {QUARTER_LABELS[quarter]?.months}
                    </SectionLabel>
                    <div className="mt-2">
                      {QUARTER_LABELS[quarter]?.months_arr.map((month) => {
                        const tuitionKey = Object.keys(structure || {}).find(
                          (k) =>
                            k.startsWith(month) &&
                            (k.includes('tuition') || k.includes('tution'))
                        )
                        const tuitionAmt = tuitionKey ? Number(structure[tuitionKey]) : 0
                        const monthTransport = transportHistory?.months?.find((m_) =>
                          m_.MonthName?.toLowerCase().startsWith(month)
                        )
                        const transportAmt =
                          includeTransport &&
                          monthTransport?.Route &&
                          monthTransport.Route !== 'N/A'
                            ? transportRoutePrice
                            : 0
                        return (
                          <div
                            key={month}
                            className="flex justify-between py-1 border-b last:border-0"
                          >
                            <span className="text-sm capitalize">
                              {month.charAt(0).toUpperCase() + month.slice(1)}
                            </span>
                            <span className="text-sm font-mono">
                              {includeTuition && tuitionAmt > 0
                                ? `₹${tuitionAmt.toLocaleString('en-IN')} tuition`
                                : ''}
                              {transportAmt > 0
                                ? ` + ₹${transportAmt.toLocaleString('en-IN')} transport`
                                : ''}
                            </span>
                          </div>
                        )
                      })}
                    </div>
                    <div className="flex justify-between items-center pt-2">
                      <span className="font-semibold">Quarter total</span>
                      <span className="text-xl font-bold text-primary">
                        ₹{quarterTotal.toLocaleString('en-IN')}
                      </span>
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}

          <div className="space-y-4 pt-4 border-t">
            {tab === 'type' && (
              <div className="rounded-2xl border bg-muted/20 p-4 space-y-3">
                <SectionLabel>Payment details</SectionLabel>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  <div>
                    <p className="text-xs text-muted-foreground mb-2">Payment mode</p>
                    <div className="flex flex-wrap gap-2">
                      {PAYMENT_MODES.map((m) => (
                        <ModeButton
                          key={m}
                          mode={m}
                          selected={commonPaymentMode === m}
                          onClick={setCommonPaymentMode}
                        />
                      ))}
                    </div>
                  </div>

                  <div>
                    <p className="text-xs text-muted-foreground mb-2">Remarks</p>
                    <Input
                      placeholder="Remarks (optional) — e.g. Cheque no. 004532"
                      value={commonRemarks}
                      onChange={(e) => setCommonRemarks(e.target.value)}
                      className="h-10 text-sm"
                    />
                  </div>
                </div>
              </div>
            )}

            <div className="flex items-center justify-between gap-4">
              <div className="text-sm text-muted-foreground">
                <span className="font-medium">Collection date: </span>
                <span>
                  {new Date(collectionDate).toLocaleDateString('en-IN', {
                    day: 'numeric',
                    month: 'short',
                    year: 'numeric',
                  })}
                </span>
              </div>
              <Button
                onClick={handleSubmit}
                disabled={isLoading}
                size="lg"
                className="gap-2 min-w-40 rounded-xl"
              >
                {isLoading ? (
                  'Processing…'
                ) : (
                  <>
                    <CheckCircle2 className="h-4 w-4" />
                    Collect Fees
                    {tab === 'type' && grandTotal > 0 && (
                      <Badge variant="secondary" className="ml-1 text-xs">
                        ₹{grandTotal.toLocaleString('en-IN')}
                      </Badge>
                    )}
                    {tab === 'quarter' && quarterTotal > 0 && (
                      <Badge variant="secondary" className="ml-1 text-xs">
                        ₹{quarterTotal.toLocaleString('en-IN')}
                      </Badge>
                    )}
                  </>
                )}
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      <FeeStructureSection
        structure={structure}
        feesData={feesData}
        transportHistory={transportHistory}
        transportFee={transportRoutePrice}
        inventory={inventory}
        studentClass={student.ClassID}
        academicYear={student.academicYear || '2025-2026'}
      />
    </>
  )
}
